# Generated by Django 3.2.4 on 2021-06-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantidade',
        ),
    ]
