# Generated by Django 3.2.4 on 2021-06-30 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210629_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_da_marca', to='base.marca'),
        ),
    ]
