# Generated by Django 3.2.3 on 2021-06-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='idade',
            field=models.CharField(max_length=2),
        ),
    ]
