# Generated by Django 3.2.4 on 2021-06-15 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_alter_pessoa_idade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoa.pessoa')),
                ('nota', models.FloatField()),
            ],
            bases=('pessoa.pessoa',),
        ),
    ]
